
name: zimage_patcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        sudo apt-get install p7zip-full wget
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        wget -q https://raw.githubusercontent.com/AndroidDump/xiaomi_olivelite_dump/olivelite-user-10-QKQ1.191014.001-V11.0.2.0.QCPINXM-release-keys/boot.img
        python ./main.py boot.img  
    - uses: actions/download-artifact@v2
      with:
        name: Test
    - name: Display structure of downloaded files
      run: ls -R
